version: "3.8"

services:
  stashaway-app:
    build:
      context: ./src
      dockerfile: dockerfiles/node.dockerfile
    command: npm run start-dev
    container_name: stashaway-node
    restart: on-failure
    depends_on:
      - stashaway-db
    tty: true
    ports: 
      - "41570:8085"
    volumes:
      - ./src/:/usr/src/app
      - /usr/src/app/src/node_modules
    environment: 
      - DATABASE_HOST=stashaway-db
      - MYSQL_DATABASE=dbname
      - MYSQL_PORT=3306
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=root
      - DATABASE_TEST_HOST=stashaway-test-db
  stashaway-db:
    image: mysql:8
    container_name: stashaway-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3309:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=root
  stashaway-test-db:
    image: mysql:8
    container_name: stashaway-test-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=root
  stashaway-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8185:80'
    restart: always
    environment:
        PMA_HOST: stashaway-db
        UPLOAD_LIMIT: 1024M
        MEMORY_LIMIT: 1024M
    depends_on:
        - stashaway-db
networks:
  default:
    name: stashaway-network
